// Build information, automatically generated by `ng-info`
const build = {
    version: "2.3.1",
    timestamp: "Fri Aug 19 2022 08:54:03 GMT+0200 (Central European Summer Time)",
    message: null,
    git: {
        user: "Cyrill Püntener",
        branch: "feature/add-route-planer",
        hash: "c20d36",
        fullHash: "c20d36846fc4b408fd436ff98b2cda71914add0c"
    }
};

export default build;