// Build information, automatically generated by `ng-info`
const build = {
    version: "2.3.0",
    timestamp: "Wed Aug 10 2022 21:07:44 GMT+0200 (Central European Summer Time)",
    message: null,
    git: {
        user: "Cyrill Püntener",
        branch: "feature/interactive_exports",
        hash: "e584f4",
        fullHash: "e584f420a0e8bb0d3294d06aa2ecb835a2862c0e"
    }
};

export default build;