// Build information, automatically generated by `ng-info`
const build = {
    version: "2.3.1",
    timestamp: "Mon Aug 15 2022 19:45:38 GMT+0200 (Central European Summer Time)",
    message: null,
    git: {
        user: "Cyrill Püntener",
        branch: "feature/add-route-planer",
        hash: "542bff",
        fullHash: "542bff58d96b04d6e2871cb4e0440523270b068b"
    }
};

export default build;