version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"

    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
      minor-and-patch:
        applies-to: security-updates
        patterns:
          - "@angular*"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "@angular*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "pip"
    directory: "/swiss_TML_api"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"