name: Backend Unit Tests

on:
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install requirements
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run unit tests
        working-directory: backend
        env:
          MPLBACKEND: Agg
        run: python -m unittest discover -s tests -t .
