name: Lint

# we run testing for both master and dev branches (but only on pull requests)
on:
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable