name: Lint

# we run testing for both master and dev branches (but only on pull requests for master)
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable